export const UserData=[
    {
       id:1,
       week:"week-1",
       userPrice:1000,
    },
    {
       id:2,
       week:'week-2',
       userPrice:2000,
    },
    {
       id:3,
       week:'week-3',
       userPrice:2000,
    },
    {
       id:4,
       week:'week-4',
       userPrice:3000,
    },
    {
       id:5,
       week:'week-5',
       userPrice:4500,
    },
    {
       id:6,
       week:'week-6',
       userPrice:5000,
    },
    {
       id:7,
       week:'week-7',
       userPrice:6000,
    },
    {
       id:8,
       week:'week-8',
       userPrice:7000,
    },
    {
       id:9,
       week:'week-9',
       userPrice:6050,
    },
    {
       id:10,
       week:'week-10',
       userPrice:600,
    },
    {
       id:11,
       week:'week-11',
       userPrice:8000,
    },
    {
       id:12,
       week:'week-12',
       userPrice:5000,
    },
    {
       id:13,
       week:'week-13',
       userPrice:6000,
    },
]